application_params:
  env: dev
db_params:
  username: rx3lixir
  password: password
  db_name: aggregator
  port: 5432
  connect_timeout: 10s
redis_params:
  url: localhost:6379
  password: ""
server_params:
  address: localhost:3000
  secret_key: 36080001349340267925113477454910
