// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CategoryID    int64                  `protobuf:"varint,4,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Price         float32                `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	Image         string                 `protobuf:"bytes,9,opt,name=image,proto3" json:"image,omitempty"`
	Source        string                 `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReq) Reset() {
	*x = EventReq{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReq) ProtoMessage() {}

func (x *EventReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReq.ProtoReflect.Descriptor instead.
func (*EventReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *EventReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventReq) GetCategoryID() int64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *EventReq) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *EventReq) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *EventReq) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EventReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *EventReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *EventReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type EventRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CategoryID    int64                  `protobuf:"varint,4,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Price         float32                `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	Image         string                 `protobuf:"bytes,9,opt,name=image,proto3" json:"image,omitempty"`
	Source        string                 `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRes) Reset() {
	*x = EventRes{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRes) ProtoMessage() {}

func (x *EventRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRes.ProtoReflect.Descriptor instead.
func (*EventRes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *EventRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventRes) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventRes) GetCategoryID() int64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *EventRes) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *EventRes) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *EventRes) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EventRes) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *EventRes) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *EventRes) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EventRes) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EventRes) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListEventsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventRes            `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRes) Reset() {
	*x = ListEventsRes{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRes) ProtoMessage() {}

func (x *ListEventsRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRes.ProtoReflect.Descriptor instead.
func (*ListEventsRes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *ListEventsRes) GetEvents() []*EventRes {
	if x != nil {
		return x.Events
	}
	return nil
}

type UserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReq) Reset() {
	*x = UserReq{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReq) ProtoMessage() {}

func (x *UserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReq.ProtoReflect.Descriptor instead.
func (*UserReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *UserReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserReq) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type UserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRes) Reset() {
	*x = UserRes{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRes) ProtoMessage() {}

func (x *UserRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRes.ProtoReflect.Descriptor instead.
func (*UserRes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *UserRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRes) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserRes) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *UserRes) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListUsersRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserRes             `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRes) Reset() {
	*x = ListUsersRes{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRes) ProtoMessage() {}

func (x *ListUsersRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRes.ProtoReflect.Descriptor instead.
func (*ListUsersRes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListUsersRes) GetUsers() []*UserRes {
	if x != nil {
		return x.Users
	}
	return nil
}

type SessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	IsRevoked     bool                   `protobuf:"varint,4,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionReq) Reset() {
	*x = SessionReq{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReq) ProtoMessage() {}

func (x *SessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReq.ProtoReflect.Descriptor instead.
func (*SessionReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *SessionReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionReq) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *SessionReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SessionReq) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

func (x *SessionReq) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type SessionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	IsRevoked     bool                   `protobuf:"varint,4,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRes) Reset() {
	*x = SessionRes{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRes) ProtoMessage() {}

func (x *SessionRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRes.ProtoReflect.Descriptor instead.
func (*SessionRes) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *SessionRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionRes) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *SessionRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SessionRes) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

func (x *SessionRes) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x02\n" +
	"\bEventReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"categoryID\x18\x04 \x01(\x03R\n" +
	"categoryID\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12.\n" +
	"\x04date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x14\n" +
	"\x05price\x18\b \x01(\x02R\x05price\x12\x14\n" +
	"\x05image\x18\t \x01(\tR\x05image\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source\"\xa6\x03\n" +
	"\bEventRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"categoryID\x18\x04 \x01(\x03R\n" +
	"categoryID\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12.\n" +
	"\x04date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x14\n" +
	"\x05price\x18\b \x01(\x02R\x05price\x12\x14\n" +
	"\x05image\x18\t \x01(\tR\x05image\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"5\n" +
	"\rListEventsRes\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.pb.EventResR\x06events\"z\n" +
	"\aUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x19\n" +
	"\bis_admin\x18\x05 \x01(\bR\aisAdmin\"\xb5\x01\n" +
	"\aUserRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x19\n" +
	"\bis_admin\x18\x05 \x01(\bR\aisAdmin\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"1\n" +
	"\fListUsersRes\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.pb.UserResR\x05users\"\xba\x01\n" +
	"\n" +
	"SessionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\x04 \x01(\bR\tisRevoked\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xba\x01\n" +
	"\n" +
	"SessionRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\x04 \x01(\bR\tisRevoked\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt2\x8a\x05\n" +
	"\n" +
	"aggregator\x12+\n" +
	"\vCreateEvent\x12\f.pb.EventReq\x1a\f.pb.EventRes\"\x00\x12(\n" +
	"\bGetEvent\x12\f.pb.EventReq\x1a\f.pb.EventRes\"\x00\x12/\n" +
	"\n" +
	"ListEvents\x12\f.pb.EventReq\x1a\x11.pb.ListEventsRes\"\x00\x12+\n" +
	"\vUpdateEvent\x12\f.pb.EventReq\x1a\f.pb.EventRes\"\x00\x12+\n" +
	"\vDeleteEvent\x12\f.pb.EventReq\x1a\f.pb.EventRes\"\x00\x12(\n" +
	"\n" +
	"CreateUser\x12\v.pb.UserReq\x1a\v.pb.UserRes\"\x00\x12%\n" +
	"\aGetUser\x12\v.pb.UserReq\x1a\v.pb.UserRes\"\x00\x12,\n" +
	"\tListUsers\x12\v.pb.UserReq\x1a\x10.pb.ListUsersRes\"\x00\x12(\n" +
	"\n" +
	"UpdateUser\x12\v.pb.UserReq\x1a\v.pb.UserRes\"\x00\x12(\n" +
	"\n" +
	"DeleteUser\x12\v.pb.UserReq\x1a\v.pb.UserRes\"\x00\x121\n" +
	"\rCreateSession\x12\x0e.pb.SessionReq\x1a\x0e.pb.SessionRes\"\x00\x12.\n" +
	"\n" +
	"GetSession\x12\x0e.pb.SessionReq\x1a\x0e.pb.SessionRes\"\x00\x121\n" +
	"\rRevokeSession\x12\x0e.pb.SessionReq\x1a\x0e.pb.SessionRes\"\x00\x121\n" +
	"\rDeleteSession\x12\x0e.pb.SessionReq\x1a\x0e.pb.SessionRes\"\x00B)Z'github.com/rx3lixir/agg-api/agg-grpc/pbb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_goTypes = []any{
	(*EventReq)(nil),              // 0: pb.EventReq
	(*EventRes)(nil),              // 1: pb.EventRes
	(*ListEventsRes)(nil),         // 2: pb.ListEventsRes
	(*UserReq)(nil),               // 3: pb.UserReq
	(*UserRes)(nil),               // 4: pb.UserRes
	(*ListUsersRes)(nil),          // 5: pb.ListUsersRes
	(*SessionReq)(nil),            // 6: pb.SessionReq
	(*SessionRes)(nil),            // 7: pb.SessionRes
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_api_proto_depIdxs = []int32{
	8,  // 0: pb.EventReq.time:type_name -> google.protobuf.Timestamp
	8,  // 1: pb.EventReq.date:type_name -> google.protobuf.Timestamp
	8,  // 2: pb.EventRes.time:type_name -> google.protobuf.Timestamp
	8,  // 3: pb.EventRes.date:type_name -> google.protobuf.Timestamp
	8,  // 4: pb.EventRes.created_at:type_name -> google.protobuf.Timestamp
	8,  // 5: pb.EventRes.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 6: pb.ListEventsRes.events:type_name -> pb.EventRes
	8,  // 7: pb.UserRes.created_at:type_name -> google.protobuf.Timestamp
	4,  // 8: pb.ListUsersRes.users:type_name -> pb.UserRes
	8,  // 9: pb.SessionReq.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 10: pb.SessionRes.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 11: pb.aggregator.CreateEvent:input_type -> pb.EventReq
	0,  // 12: pb.aggregator.GetEvent:input_type -> pb.EventReq
	0,  // 13: pb.aggregator.ListEvents:input_type -> pb.EventReq
	0,  // 14: pb.aggregator.UpdateEvent:input_type -> pb.EventReq
	0,  // 15: pb.aggregator.DeleteEvent:input_type -> pb.EventReq
	3,  // 16: pb.aggregator.CreateUser:input_type -> pb.UserReq
	3,  // 17: pb.aggregator.GetUser:input_type -> pb.UserReq
	3,  // 18: pb.aggregator.ListUsers:input_type -> pb.UserReq
	3,  // 19: pb.aggregator.UpdateUser:input_type -> pb.UserReq
	3,  // 20: pb.aggregator.DeleteUser:input_type -> pb.UserReq
	6,  // 21: pb.aggregator.CreateSession:input_type -> pb.SessionReq
	6,  // 22: pb.aggregator.GetSession:input_type -> pb.SessionReq
	6,  // 23: pb.aggregator.RevokeSession:input_type -> pb.SessionReq
	6,  // 24: pb.aggregator.DeleteSession:input_type -> pb.SessionReq
	1,  // 25: pb.aggregator.CreateEvent:output_type -> pb.EventRes
	1,  // 26: pb.aggregator.GetEvent:output_type -> pb.EventRes
	2,  // 27: pb.aggregator.ListEvents:output_type -> pb.ListEventsRes
	1,  // 28: pb.aggregator.UpdateEvent:output_type -> pb.EventRes
	1,  // 29: pb.aggregator.DeleteEvent:output_type -> pb.EventRes
	4,  // 30: pb.aggregator.CreateUser:output_type -> pb.UserRes
	4,  // 31: pb.aggregator.GetUser:output_type -> pb.UserRes
	5,  // 32: pb.aggregator.ListUsers:output_type -> pb.ListUsersRes
	4,  // 33: pb.aggregator.UpdateUser:output_type -> pb.UserRes
	4,  // 34: pb.aggregator.DeleteUser:output_type -> pb.UserRes
	7,  // 35: pb.aggregator.CreateSession:output_type -> pb.SessionRes
	7,  // 36: pb.aggregator.GetSession:output_type -> pb.SessionRes
	7,  // 37: pb.aggregator.RevokeSession:output_type -> pb.SessionRes
	7,  // 38: pb.aggregator.DeleteSession:output_type -> pb.SessionRes
	25, // [25:39] is the sub-list for method output_type
	11, // [11:25] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
